name: ClassicCarBot

on:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir tetiklenir
  workflow_dispatch:        # Manuel tetiklemeye izin verir

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests

    - name: Run bot script
      env:
        TW_API_KEY: ${{ secrets.TW_API_KEY }}
        TW_API_SECRET: ${{ secrets.TW_API_SECRET }}
        TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
        TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
        UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
      run: python main.py
